#!/usr/bin/env bash

flask db upgrade
if [ "$FLASK_ENV" = "development" ] 
then
  python -m flask run --host=0.0.0.0 --port=$FLASK_PORT  
else
  waitress-serve --port=$FLASK_PORT --call 'app:create_app' 
fi
